// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package csharpcode;

@net.sf.jni4net.attributes.ClrType
public class AddTwoNumbers extends system.Object {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected AddTwoNumbers(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrConstructor("()V")
    public AddTwoNumbers() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
        csharpcode.AddTwoNumbers.__ctorAddTwoNumbers0(this);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    private native static void __ctorAddTwoNumbers0(net.sf.jni4net.inj.IClrProxy thiz);
    
    @net.sf.jni4net.attributes.ClrMethod("()V")
    public native static void AddTwoNumbers2And3();
    
    public static system.Type typeof() {
        return csharpcode.AddTwoNumbers.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        csharpcode.AddTwoNumbers.staticType = staticType;
    }
    //</generated-proxy>
}
